//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsManagement.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProductsManagement.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        internal static string AddProductRes {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        internal static string RemoveProductRes {
            get {
                return ResourceManager.GetString("RemoveProduct", resourceCulture);
            }
        }
        
        internal static string FindProductRes {
            get {
                return ResourceManager.GetString("FindProduct", resourceCulture);
            }
        }
        
        internal static string SaveXmlRes {
            get {
                return ResourceManager.GetString("SaveXml", resourceCulture);
            }
        }
        
        internal static string LoadXmlRes {
            get {
                return ResourceManager.GetString("LoadXml", resourceCulture);
            }
        }
        
        internal static string EditDatabaseRes {
            get {
                return ResourceManager.GetString("EditDatabase", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string ManufacturerName {
            get {
                return ResourceManager.GetString("ManufacturerName", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string StorageQuantity {
            get {
                return ResourceManager.GetString("StorageQuantity", resourceCulture);
            }
        }
        
        internal static string ManufacturerUNP {
            get {
                return ResourceManager.GetString("ManufacturerUNP", resourceCulture);
            }
        }
        
        internal static string TotalSelected {
            get {
                return ResourceManager.GetString("TotalSelected", resourceCulture);
            }
        }
        
        internal static string DeleteChosenProducts {
            get {
                return ResourceManager.GetString("DeleteChosenProducts", resourceCulture);
            }
        }
        
        internal static string FindProducts {
            get {
                return ResourceManager.GetString("FindProducts", resourceCulture);
            }
        }
        
        internal static string DeleteProducts {
            get {
                return ResourceManager.GetString("DeleteProducts", resourceCulture);
            }
        }
        
        internal static string TotalProducts {
            get {
                return ResourceManager.GetString("TotalProducts", resourceCulture);
            }
        }
    }
}
